---

# Boxed installation playbook
# ---------------------------

# A Simple, straight playbook for producing
# a boxed installation in a vagrant VM.


- name: 'Grafana boxed installation'

  hosts: vagrant

  roles:
    - '.'    # This role itself

