---

# Simple, straight playbook for boxed Grafana installs

- name: 'Grafana boxed installation'

  hosts: vagrant

  pre_tasks:
    - name: APT update
      sudo: yes
      when: ansible_os_family == 'Debian'
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - '.'    # This role itself

