---

- name: Prepare Grafana install dir
  sudo: yes
  file:
    dest: "{{grafana_deploy_path}}"
    state: directory
  tags:
    - deps
    - grafana
    - monitoring

- name: Download Grafana release tarball
  sudo: yes
  get_url:
    url: "{{grafana_package_url}}"
    dest: "/tmp/{{grafana_package}}.tar.gz"
  tags:
    - deps
    - grafana
    - monitoring

- name: Install Grafana from tarball
  sudo: yes
  unarchive:
    copy: no
    src: "/tmp/{{grafana_package}}.tar.gz"
    dest: "{{grafana_deploy_path}}"
    owner: "{{grafana_deploy_user}}"
    group: "{{grafana_deploy_group}}"
  tags:
    - deps
    - grafana
    - monitoring
